name: calliope

channels:
    - conda-forge

dependencies:
    - bottleneck
    - click
    - glpk=4.61
    - hdf5
    - ipython
    - ipdb
    - jinja2
    - libnetcdf
    - natsort
    - netcdf4
    - numexpr
    - numpy
    - pandas<0.26
    - plotly<4.0
    - pyomo<5.7
    - pytest<5.3  # 5.3 fails with KeyError: '__name__' when collecting items
    - pytest-cov
    - pytest-xdist  # pytest distributed testing plugin
    - ruamel.yaml<0.17
    - scikit-learn<0.23
    - xarray<0.15
